FROM smartgic/ovos-skill-base:testing


USER root
# Install requests
RUN . ~/.venv/bin/activate && \
    pip install --no-cache-dir requests ovos-skill-launcher


RUN mkdir -p skill
RUN mkdir -p /skill/skill-vehicle-control

COPY --chown=ovos:ovos ./skill-vehicle-control /skill/skill-vehicle-control/

# COPY --chown=ovos:ovos test.py test.py

USER ovos

# Set PYTHONPATH
WORKDIR /skill

CMD ["python3", "-m", "ovos_skill_launcher"]