# docker compose -f docker-compose-test.debug.yml build
# docker compose -f docker-compose-test.debug.yml up
# docker compose -f docker-compose-test.debug.yml restart

services:
  ovos_skill_test:
    build:
      context: /home/ovos/ovos-docker-install/ovos-skill-test
      dockerfile: Dockerfile_debug.test_skill

    container_name: ovos_skill_test

    network_mode: host

    ports:
      - "5678:5678"

    environment:
      - TZ=Europe/Berlin
      - OVOS_BUS_HOST=127.0.0.1
  # python -Xfrozen_modules=off \
    command:
      - sh
      - -c
      - |
          python \
          -Xfrozen_modules=off \
          -m debugpy \
          --wait-for-client \
          --listen 0.0.0.0:5678 \
          /home/ovos/.venv/bin/ovos-skill-launcher \
          my-skill-test.openvoiceos
      
    volumes:
      - /home/ovos/ovos-docker-install/ovos-skill-test:/home/ovos/skill/ovos-skill-test
      - ~/ovos/config:/home/ovos/.config/mycroft
      - ~/ovos/ovos-share:/home/ovos/.local/share/mycroft