# Use the Skill Base, not the Core (unless you want to run the whole brain here)
FROM smartgic/ovos-skill-base:stable

USER root

# 🔒 1. Pin setuptools to avoid pkg_resources deprecation warning
RUN pip install --no-cache-dir "setuptools<81" requests

# 1. Install dependencies
# We use 'pip' which usually points to the venv in these images
RUN pip install --no-cache-dir requests

# 2. Setup skill directory
RUN mkdir -p /home/ovos/skill/ovos-skill-test

COPY --chown=ovos:ovos . /home/ovos/skill/ovos-skill-test/

WORKDIR /home/ovos/skill/ovos-skill-test

RUN pip install .

# 3. Environment Setup
# Ensure the venv bin is in the PATH so 'ovos-skill-launcher' can be found
ENV PATH="/home/ovos/.venv/bin:$PATH"
#ENV PYTHONPATH="/skill:/skill/ovos-skill-test:$PYTHONPATH"

USER ovos
# WORKDIR /skill/ovos-skill-test

# 4. Launch the skill
# CMD ["/bin/sh", "-c", "python skill_test/test.py"]
# 5. The command that actually starts your skill/app
# CMD ["python", "skill_test"]
CMD ["ovos-skill-launcher", "my-skill-test.openvoiceos"]