# docker-compose.debug.yml
# docker compose -f docker-compose-test.debug.yml up

services:
  ovos_skill_test:
    build:
      context: /home/ovos/ovos-docker-install/ovos-skill-test
      dockerfile: Dockerfile_debug.test_skill
    container_name: ovos_skill_test
    ports:
      - "5678:5678"
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Berlin
      - OVOS_BUS_HOST=127.0.0.1
    # CMD ["ovos-skill-launcher", "my-skill-test.openvoiceos"]
    command:
      - "sh"
      - "-c"
      - |
        pip install debugpy -t /tmp \
        && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 \
        -m ovos-skill-launcher my-skill-test.openvoiceos
    volumes:
      - ~/ovos/config:/home/ovos/.config/mycroft
      - ~/ovos/ovos-share:/home/ovos/.local/share/mycroft